const images = {
  '49ers': require('./49ers.png'),
  AFC: require('./AFC.png'),
  Bears: require('./Bears.png'),
  Bengals: require('./Bengals.png'),
  Bills: require('./Bills.png'),
  Broncos: require('./Broncos.png'),
  Browns: require('./Browns.png'),
  Buccaneers: require('./Buccaneers.png'),
  Cardinals: require('./Cardinals.png'),
  Chargers: require('./Chargers.png'),
  Chiefs: require('./Chiefs.png'),
  Colts: require('./Colts.png'),
  Cowboys: require('./Cowboys.png'),
  Dolphins: require('./Dolphins.png'),
  Eagles: require('./Eagles.png'),
  Falcons: require('./Falcons.png'),
  Giants: require('./Giants.png'),
  Jaguars: require('./Jaguars.png'),
  Jets: require('./Jets.png'),
  Lions: require('./Lions.png'),
  NFC: require('./NFC.png'),
  Oilers: require('./Oilers.png'),
  Packers: require('./Packers.png'),
  Panthers: require('./Panthers.png'),
  Patriots: require('./Patriots.png'),
  Raiders: require('./Raiders.png'),
  Rams: require('./Rams.png'),
  Ravens: require('./Ravens.png'),
  Redskins: require('./Redskins.png'),
  Saints: require('./Saints.png'),
  Seahawks: require('./Seahawks.png'),
  Steelers: require('./Steelers.png'),
  Texans: require('./Texans.png'),
  Titans: require('./Titans.png'),
  Vikings: require('./Vikings.png')
}
export default images;